include ../../../base.mk

PROTONS_PATH=../../../

DATASET = LHC16g-muon-calo-pass1
DPART = first
MC = kFALSE

TEST_SELECTION = PhysTender

%.cxx:
	@echo "Don't importa libraries use AliPhysics versions instead"
