include ../../../base.mk

PROTONS_PATH=../../../

DATASET = LHC16g
DPART = first
MC = kTRUE
OUTDIR = results/mc/pythia/debug_weights


TEST_SELECTION = PhysTender

%.cxx:
	@echo "Starting the analysis"
