include ../../../base.mk

PROTONS_PATH=../../../

DATASET = LHC17d20a2_extra
DPART = first
MC = kTRUE
OUTDIR = results/mc/pythia/debug_weights


TEST_SELECTION = PhysTender

%.cxx:
	@echo "Starting the analysis"
