include ../../base.mk

DATASET = LHC16l-muon-calo-pass1
DPART = first
MC = kFALSE
OUTDIR = results/data/corrected/

#DATASET = LHC17d20a2_extra
#DPART = second
#MC = kTRUE
#OUTDIR = results/mc/pythia

TEST_SELECTION = PhysTender

%.cxx:
	@$(call funlink)
