.PHONY: test clean

test:
	./runTest.sh

clean:
	rm -rf lego_train.sh lego_train_merge.C lego_train_merge.sh lego_train_validation.sh lego_train_validation_merge.sh stderr stdout lego_train.root *.log